/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.cadAluno;
import Modelo.Aluno;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Cadastro_aluno extends javax.swing.JFrame {

    /**
     * Creates new form Cadastro_aluno
     */
    public Cadastro_aluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nome_aluno = new javax.swing.JTextField();
        email_aluno = new javax.swing.JTextField();
        cpf_aluno = new javax.swing.JFormattedTextField();
        nascimento_aluno = new javax.swing.JFormattedTextField();
        curso_aluno = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        desativ_aluno = new javax.swing.JButton();
        ativ_aluno = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        Cadastro_aluno = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cadastrar aluno");

        jLabel2.setText("Nome:");

        jLabel3.setText("CPF:");

        jLabel4.setText("Email");

        jLabel5.setText("Nascimento:");

        jLabel6.setText("Curso:");

        nome_aluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nome_alunoKeyTyped(evt);
            }
        });

        try {
            cpf_aluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            nascimento_aluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("## / ## / ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton1.setText("Cadastrar aluno");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        desativ_aluno.setText("Desativar aluno");
        desativ_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desativ_alunoActionPerformed(evt);
            }
        });

        ativ_aluno.setText("Ativar aluno");
        ativ_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ativ_alunoActionPerformed(evt);
            }
        });

        jMenu3.setText("Aluno");

        jMenuItem4.setText("Cadastrar aluno em curso");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem1.setText("Atualizar dados do aluno");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar2.add(jMenu3);

        Cadastro_aluno.setText("Curso");
        Cadastro_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastro_alunoActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Cadastrar/remover curso");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Cadastro_aluno.add(jMenuItem3);

        jMenuBar2.add(Cadastro_aluno);

        jMenu1.setText("Consulta");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(27, 27, 27)
                        .addComponent(desativ_aluno)
                        .addGap(26, 26, 26)
                        .addComponent(ativ_aluno)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(email_aluno))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nome_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(cpf_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nascimento_aluno)
                            .addComponent(curso_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(nome_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cpf_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(nascimento_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(curso_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(email_aluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(desativ_aluno)
                    .addComponent(ativ_aluno))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cadastro_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastro_alunoActionPerformed

    }//GEN-LAST:event_Cadastro_alunoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new Cadastro_curso().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String[] dados = {nome_aluno.getText(), 
            cpf_aluno.getText(), 
            email_aluno.getText(),
            curso_aluno.getText(),
            nascimento_aluno.getText()
        };
        
        for(String dado:dados){
            if(dado.isEmpty() || dado == null){
                JOptionPane.showMessageDialog(null, "Preencha todos os campos corretamente");
            }
        }
        
            cadAluno al = new cadAluno();
            Aluno aluno = new Aluno();
            
            aluno.setNome(nome_aluno.getText());
            
            boolean v = al.verifCurso(curso_aluno.getText());
            boolean v1 = al.verifCPF(cpf_aluno.getText());
            boolean v2 = al.verifEmail(email_aluno.getText());
            boolean v3 = al.verifIdade(nascimento_aluno.getText());
            String v4 = al.sitSQL(cpf_aluno.getText());
            
            
            if("desativado".equals(v4)){
                int resposta = JOptionPane.showConfirmDialog(null, 
                        "Cadastro encontrado, porém desativado, deseja ativar novamente o cadastro?", "Pergunta", 
                        JOptionPane.YES_NO_OPTION);
                if(resposta == JOptionPane.YES_OPTION){
                    aluno.setCpf(cpf_aluno.getText());
                    al.ativarAluno(aluno);
                    
                    if(!al.curso(curso_aluno.getText())){
                        JOptionPane.showMessageDialog(null, "O curso digitado não existe!");
                        return;
                    }
                    
                    int sqlreturn = al.limiteCurso(curso_aluno.getText());
                    int limite = al.limitesql(curso_aluno.getText());
                
                    if(sqlreturn >= limite){
                        JOptionPane.showMessageDialog(null, "O curso já atingiu o limite de cadastro, selecione ou crie outro!");
                        curso_aluno.setText("");
                        return;
                    }else{
                        aluno.setCurso(curso_aluno.getText());
                    }
                    JOptionPane.showMessageDialog(null, "Cadastro de aluno ativo com sucesso!");
                    return;
                }else{
                    JOptionPane.showMessageDialog(null, "Cadastro não ativo.");
                    return;
                }
            }
       
            if(v1 == false){
                JOptionPane.showMessageDialog(null, "O cpf digitado está inválido!");
                cpf_aluno.setText("");
            }else{
                if(al.cpfSQL(cpf_aluno.getText()) == true){
                   JOptionPane.showMessageDialog(null, "O cpf digitado já está em uso!"); 
                   cpf_aluno.setText("");
                   return;
                }else{
                    aluno.setCpf(cpf_aluno.getText());
            }
            }
            
            if(v == false){
                JOptionPane.showMessageDialog(null, "O curso digitado não existe, verifique a escrita ou tente novamente");
                curso_aluno.setText("");
            }else{
                int sqlreturn = al.limiteCurso(curso_aluno.getText());
                int limite = al.limitesql(curso_aluno.getText());
                
                if(sqlreturn >= limite){
                    JOptionPane.showMessageDialog(null, "O curso já atingiu o limite de cadastro, selecione ou crie outro!");
                    curso_aluno.setText("");
                    return;
                }else{
                    aluno.setCurso(curso_aluno.getText());
                }
            }
            
            if(v2 == false){
                JOptionPane.showMessageDialog(null, "Email no formato inválido, digite novamente");
                email_aluno.setText("");
            }else{
                aluno.setEmail(email_aluno.getText());
            }
            
            if(v3 == false){
                JOptionPane.showMessageDialog(null, "O usuário deve ter mais de 16 anos");
            }else{
                aluno.setNascimento(nascimento_aluno.getText());
                System.out.println(aluno.getNascimento());
            }
            
            if(v == true && v1 == true && v2 == true && v3 == true){
                al.adicionarAluno(aluno);
            }   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nome_alunoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nome_alunoKeyTyped
        char c = evt.getKeyChar();
        
        if(Character.isDigit(c)){
           evt.consume();
        }
    }//GEN-LAST:event_nome_alunoKeyTyped

    private void desativ_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desativ_alunoActionPerformed
        cadAluno al = new cadAluno();
        Aluno aluno = new Aluno();
        boolean v1 = al.verifCPF(cpf_aluno.getText());
        
        if(v1 == false){
            JOptionPane.showMessageDialog(null, "O cpf digitado está inválido!");
            cpf_aluno.setText("");
        }else{
            aluno.setCpf(cpf_aluno.getText());
            al.desativarAluno(aluno);
            al.removerCurso(aluno);
            JOptionPane.showMessageDialog(null, "Cadastro de aluno desativado com sucesso!");
        }
    }//GEN-LAST:event_desativ_alunoActionPerformed

    private void ativ_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ativ_alunoActionPerformed
        cadAluno al = new cadAluno();
        Aluno aluno = new Aluno();
        boolean v1 = al.verifCPF(cpf_aluno.getText());
        
        if(v1 == false){
            JOptionPane.showMessageDialog(null, "O cpf digitado está inválido!");
            cpf_aluno.setText("");
        }else{
            aluno.setCpf(cpf_aluno.getText());
            al.ativarAluno(aluno);
            JOptionPane.showMessageDialog(null, "Cadastro de aluno ativo com sucesso!");
        }
    }//GEN-LAST:event_ativ_alunoActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new Aluno_em_curso().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
  
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        new Alunos_cadastrados().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new update_aluno().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cadastro_aluno aluno = new Cadastro_aluno();
                aluno.setVisible(true);
                aluno.setTitle("Cadastrar aluno");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Cadastro_aluno;
    private javax.swing.JButton ativ_aluno;
    private javax.swing.JFormattedTextField cpf_aluno;
    private javax.swing.JTextField curso_aluno;
    private javax.swing.JButton desativ_aluno;
    private javax.swing.JTextField email_aluno;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JFormattedTextField nascimento_aluno;
    private javax.swing.JTextField nome_aluno;
    // End of variables declaration//GEN-END:variables
}

